DELETE http://localhost:8080/api/seance/delete/6238e26494ea427d1d1771b9
Accept: application/json

###
GET http://localhost:8080/api/seance/getById/6238e29f9788553cb0635ac6
Accept: application/json

###
GET http://localhost:8080/api/seance/all
Accept: application/json

###
POST http://localhost:8080/api/seance/creerSeance
Content-Type: application/json


{
  "createurSeance": {
    "fonction": "MEMBRE ADMINISTRATIF",
    "nomUtilisateur": "MAUBERT",
    "prenomUtilisateur": "FLORENCE",
    "email": "florence.maubert@univ-orleans.fr",
    "motDePasse": "florence",
    "roles": [
      "MEMBRE ADMINISTRATIF",
      "CREER SEANCE"
    ]
  },
  "discipline": "TEST ET QUALITÉ",
  "enseignant": {
    "fonction": "ENSEIGNANT",
    "nomUtilisateur": "Boichut",
    "prenomUtilisateur": "Yohann",
    "email": "boichut.yohannn@univ-orleans.fr",
    "motDePasse": "matthieu",
    "roles": [
      "ENSEIGNANT",
      "VALIDER SEANCE"
    ]
  },
  "typeSeance": "CM",
  "groupe": {
    "groupeDeTD": "TD2",
    "groupeDeTP": "TP3"
  },
  "heureDebut": "2020-05-07T11:02:00",
  "heureFin": "2020-05-07T11:00:00",
  "statutSeance": "NON VALIDE"
}
###

