POST http://localhost:8080/api/emargement/secretaires
Content-Type: application/json

{
  "nom": "Dupuy",
  "prenom": "Brigitte",
  "email": "brigitte.dupuy@univ-orleans.fr",
  "motDePasse": "mdp",
  "roles": [
    "MEMBRE_ADMINISTRATIF"
  ]
}

####
POST http://localhost:8080/api/emargement/secretaires
Content-Type: application/json

{
  "nom": "Maubert",
  "prenom": "Florence",
  "email": "florence.maubert@univ-orleans.fr",
  "motDePasse": "mdp",
  "roles": [
    "MEMBRE_ADMINISTRATIF"
  ]
}


####
POST http://localhost:8080/api/emargement/secretaires
Content-Type: application/json

{
  "nom": "secretariat",
  "prenom": "",
  "email": "secretariat@univ-orleans.fr",
  "motDePasse": "mdp",
  "roles": [
    "MEMBRE_ADMINISTRATIF"
  ]
}

###

GET http://localhost:8080/api/emargement/secretaires