GET http://localhost:8080/api/utilisateur/enseignants
Accept: application/json

###
GET http://localhost:8080/api/utilisateur/etudiants
Accept: application/json

###
GET http://localhost:8080/api/utilisateur/promotion/MASTER 1/2021
Accept: application/json

###
GET http://localhost:8080/api/utilisateur/promotion/MASTER 1
Accept: application/json
###

DELETE http://localhost:8080/api/delete/6239eb78c203c90b13bfab43
Accept: application/json

###
PUT http://localhost:8080/api/utilisateur/update
Accept: application/json

{
  "idUtilisateur": "6238a666545c22363f41c588",
  "numeroEtudiant": "o2175246",
  "fonction": "ETUDIANT",
  "nomUtilisateur": "KONE",
  "prenomUtilisateur": "MOUSSA MOHAMED",
  "promo":
         {
           "niveau": "MASTER 1",
           "annee": "2022"
         },
  "email": "moussa.kone@etu.univ-orleans.fr",
  "motDePasse": "Kmm@1999",
  "roles": [
    "ETUDIANT","EMARGEMENT"
  ]

}
###
GET http://localhost:8080/api/allUtilisateurs
Accept: application/json

###

GET http://localhost:8080/api/getById/6238a2375bb773217b58d5a9
Accept: application/json

###
POST http://localhost:8080/api/utilisateur/creerUtilisateur
Content-Type: application/json

{
  "numeroEtudiant": "o22002589",
  "fonction": "ETUDIANT",
  "nomUtilisateur": "BAKAYOKO",
  "prenomUtilisateur": "MOUSSA",
  "promo":
         {
           "niveau": "MASTER 1",
           "annee": "2022"
         },
  "email": "moussa.bakayoko@etu.univ-orleans.fr",
  "motDePasse": "@Jason09",
  "roles": [
    "ETUDIANT","EMARGEMENT"
  ]

}

###
POST http://localhost:8080/api/utilisateur/creerUtilisateur
Content-Type: application/json

{
  "numeroEtudiant": "o22002589",
  "fonction": "ETUDIANT",
  "nomUtilisateur": "fatima",
  "prenomUtilisateur": "elbardi",
  "promo":
  {
    "niveau": "MASTER 1",
    "annee": "2021"
  },
  "email": "moussa.bakayoko@etu.univ-orleans.fr",
  "motDePasse": "@Jason09",
  "roles": [
    "ETUDIANT","EMARGEMENT"
  ]

}

###
POST http://localhost:8080/api/utilisateur/creerUtilisateur
Content-Type: application/json

{
  "fonction": "ENSEIGNANT",
  "nomUtilisateur": "BOICHUT",
  "prenomUtilisateur": "YOHAN",
  "email": "yohan.boichut@univ-orleans.fr",
  "motDePasse": "yohan",
  "roles": [
    "ENSEIGNANT","VALIDER SEANCE"
  ]

}

###
POST http://localhost:8080/api/utilisateur/creerUtilisateur
Content-Type: application/json

{
  "fonction": "MEMBRE ADMINISTRATIF",
  "nomUtilisateur": "MAUBERT",
  "prenomUtilisateur": "FLORENCE",
  "email": "florence.maubert@univ-orleans.fr",
  "motDePasse": "florence",
  "roles": [
    "MEMBRE ADMINISTRATIF","CREER SEANCE"
  ]
}



