DELETE http://localhost:8080/api/seance/delete/6238e26494ea427d1d1771b9
Accept: application/json

###
GET http://localhost:8080/api/seance/getById/6238e29f9788553cb0635ac6
Accept: application/json

###
GET http://localhost:8080/api/seance/all
Accept: application/json

###
POST http://localhost:8080/api/emergement/seance
Content-Type: application/json

{
  "createurSeance": "624733dd522eca380ed8cd77",
  "discipline": "Systeme répatition",
  "enseignantID": "6247341b522eca380ed8cd78",
  "typeSeance": "TD",
  "groupe": {
    "groupeDeTD": "TD2",
    "groupeDeTP": ""
  },
  "numEtudiants": [
    "o22002589",
    "o2175246"
  ],
  "heureDebut": "2022-04-03T23:15:00",
  "heureFin": "2022-04-04T01:15:00",
  "statutSeance": "NON VALIDE"
}
###

PUT http://localhost:8080/api/emergement/seance/624a13b8d893233ac3935b91/pointage/o22002589
Accept: application/json

####
GET http://localhost:8080/api/emergement/seance/624a13b8d893233ac3935b91/etudiant-present