DELETE http://localhost:8080/api/seances/delete/6238e26494ea427d1d1771b9
Accept: application/json

####
GET http://localhost:8080/api/seances/getById/6238e29f9788553cb0635ac6
Accept: application/json

####
GET http://localhost:8080/api/seances/
Accept: application/json

####
POST http://localhost:8080/api/emargement/seances
Content-Type: application/json
Authorization: Basic brigitte.dupuy@univ-orleans.fr mdp

{
  "userID": "624733dd522eca380ed8cd77",
  "discipline": "Test et Qualité",
  "enseignantID": "yohan.boichut@univ-orleans.fr",
  "typeSeance": "TD",
  "groupe": {
    "groupeDeTD": "TD2",
    "groupeDeTP": ""
  },
  "promotion": {
    "niveau" : "MASTER 1",
    "annee" : "2022"
  },
  "heureDebut": "2022-05-17T00:15:00",
  "heureFin": "2022-05-17T02:55:00",
  "statutSeance": "NON VALIDE",
  "idSalle": "E18"
}
###

PUT http://localhost:8080/api/emargement/seances/6282d1307a2e955e5d6a82c7/pointage/o22010238/2022-05-17T00:45:00?idSalle=E12
Accept: application/json
Authorization: Basic robot@univ-orleans.fr salle

####
GET http://localhost:8080/api/emargement/seances/624b6be231b295383b70f2c7/etudiants-presents

####
GET http://localhost:8080/api/emargement/seances/624b6be231b295383b70f2c7/etudiants-absents


####
POST http://localhost:8080/api/emargement/seances
Content-Type: application/json

{
  "userID": "624733dd522eca380ed8cd77",
  "discipline": "Système répatition",
  "enseignantID": "martins.delacourt@univ-orleans.fr",
  "typeSeance": "TP",
  "groupe": {
    "groupeDeTD": "",
    "groupeDeTP": "TP3"
  },
  "promotion": {
    "niveau": "MASTER 1",
    "annee": "2022"
  },
  "heureDebut": "2022-05-17T00:15:00",
  "heureFin": "2022-05-17T02:55:00",
  "statutSeance": "NON VALIDE",
  "idSalle": "E12"
}
