POST http://localhost:8080/api/emergement/secretaire
Content-Type: application/json

{
  "nom": "MAUBERT",
  "prenom": "FLORENCE",
  "email": "florence.maubert@univ-orleans.fr",
  "motDePasse": "florence",
  "roles": [
    "MEMBRE ADMINISTRATIF","CREER SEANCE"
  ]
}

###

GET http://localhost:8080/api/emergement/secretaires