POST http://localhost:8080/api/emargement/enseignants
Content-Type: application/json

{
  "nom": "DELACOURT",
  "prenom": "MARTINS",
  "email": "martins.delacourt@univ-orleans.fr",
  "motDePasse": "martins",
  "roles": [
    "PROF", "MEMBRE_ADMINISTRATIF"
  ]
}

###
POST http://localhost:8080/api/emargement/enseignants
Content-Type: application/json

{
"nom": "Boichut",
"prenom": "Yohan",
"email": "yohan.boichut@univ-orleans.fr",
"motDePasse": "mdp",
"roles": [
"PROF", "MEMBRE_ADMINISTRATIF"
]
}



###
GET http://localhost:8080/api/emargement/enseignants

###
GET http://localhost:8080/api/emargement/enseignants
Authorization: Basic yohan.boichut@univ-orleans.fr mdp

###
GET http://localhost:8080/api/emargement/enseignants
Authorization: Basic solomon.lourdessamy@etu.univ-orleans.fr @Jason09