

DELETE http://localhost:8080/api/delete/62368a60bd61507b772a2fa9
Accept: application/json

###
PUT http://localhost:80/api/update
Accept: application/json

{
  "id": "62368a60bd61507b772a2fa9",
  "numeroEtudiant": "Mister",
  "nomEtudiant": null,
  "prenomEtudiant": null,
  "adresseMail": null,
  "promo": {
    "niveau": null,
    "annee": "2023"
  }
}
###
GET http://localhost:8080/api/all
Accept: application/json

###

GET http://localhost:8080/api/getById/62368a60bd61507b772a2fa9
Accept: application/json

###
POST http://localhost:8080/api/creerUtilisateur
Content-Type: application/json

{
  "numeroEtudiant": "o2175246",
  "nomEtudiant": "KONE",
  "prenomEtudiant": "MOUSSA",
  "adresseMail": "moussa.kone@etu.univ-orleans.fr",
  "promo":
         {
           "niveau": "MASTER 1",
           "annee": "2022"
          }
}

###
